version: '3.8'

services:
  postgres:
    build:
      context: ./docker
      dockerfile: Dockerfile-postgres
    container_name: transfer_postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: transfer_redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app_network

  nest:
    build: .
    container_name: transfer_nest
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
